add RabbitMQ Add-On documentation page
syseleven/grav-docs-metakube pull request #114
Opened 2020-07-23 08:51 UTC by furkhat

2020-07-23 11:37 UTC, phiphi282 requested changes
Looks pretty good, only found some minor linguistic stuff.

2020-07-23 11:37 UTC, phiphi282 commented on pages/03.addons/13.metakube-rabbitmq/default.en.md
> +After the installation of the Add-On you can retrive the RabbitMQ credentials with the following command:
```suggestion
After the installation of the Add-On you can retrieve the RabbitMQ credentials with the following command:
```

2020-07-23 11:37 UTC, phiphi282 commented on pages/03.addons/13.metakube-rabbitmq/default.en.md
> +When installing RabbitMQ corresponding Kubernetes services are created. You can use Kubernetes mechanisms to reach to Add-On Pods using following services:
```suggestion
When installing RabbitMQ corresponding Kubernetes services are created. You can use Kubernetes mechanisms to reach to Add-On Pods using the following services:
```

2020-07-23 12:21 UTC, furkhat commented
@phiphi282 updated

2020-07-23 12:32 UTC, phiphi282 approved these changes
lgtm

2020-07-30 12:16 UTC, eduardostalinho commented
LGTM

2020-07-30 12:18 UTC, merged