Add keycloak-gatekeeper tutorial
syseleven/grav-docs-metakube pull request #118
Opened 2020-08-19 14:55 UTC by vandersonmota

This is a simplified flow based on the internal doc I initially created. I added "vanilla" k8s yamls for this example.

2020-08-24 07:27 UTC, stefanandres requested changes

2020-08-24 07:27 UTC, stefanandres commented on pages/04.tutorials/27.setup-jwt-authentication-with-keycloak-gatekeeper/default.en.md
> +- On **Advanced settings** it is advisable to increase the **Access token lifespan**,
why and to what value shall it be increased?

2020-08-24 07:27 UTC, stefanandres commented on pages/04.tutorials/27.setup-jwt-authentication-with-keycloak-gatekeeper/default.en.md
> +Finally, you'll need to add an user to be used by your API's client applications.
add an user to where? the realm?

2020-08-24 07:27 UTC, stefanandres commented on pages/04.tutorials/27.setup-jwt-authentication-with-keycloak-gatekeeper/default.en.md
> +```
can you add an example on how authentication then looks like / what the requests/responses are? e.g. some curl or some other simple app

2020-08-24 07:29 UTC, stefanandres commented on pages/04.tutorials/27.setup-jwt-authentication-with-keycloak-gatekeeper/default.en.md
> +For applications that are API-only, setting up authentication with JWT tokens is a reasonable choice,
please add an example for what scenario where you might use this to get a broader overview for whom this tutorial is for

2020-08-25 09:31 UTC, vandersonmota commented
@stefanandres I think I made the changes you requested, plus changed a few other things for clarity.

2020-08-25 13:10 UTC, stefanandres approved these changes

2020-08-25 13:10 UTC, merged