Document how to use external-dns with OpenStack DNSaaS
syseleven/grav-docs-metakube pull request #58
Opened 2019-09-03 12:38 UTC by shahbazn

2019-09-03 13:02 UTC, mbernhardtSys11 commented
Looks good. 👍

2019-09-04 10:01 UTC, cbeneke requested changes

2019-09-04 10:01 UTC, cbeneke commented on pages/04.tutorials/23.use-external-dns/default.en.md
> +All domain names that are ExternalDNS is going to create must belong to one of DNS zones created in advance. Here is an example of how to create `example.com` DNS zone:
This seems to be a typo: "..that are ExternalDNS is going to.."

2019-09-04 10:01 UTC, cbeneke commented on pages/04.tutorials/23.use-external-dns/default.en.md
> +For easy deployment use our fully managed [External DNS Add-on](https://docs.syseleven.de/metakube/de/addons/metakube-external-dns)
Please use a relative link here (../../03.addons/[...]/default.en.md)

2019-09-04 11:02 UTC, cbeneke requested changes

2019-09-04 11:02 UTC, cbeneke commented on pages/04.tutorials/23.use-external-dns/default.en.md
> +### Deploy ExternalDNS
This heading should be something like for AWS (e.g. "Create a values.yaml file to configure Designate as external DNS provider"). Because the actual deployment happens in a later step

2019-09-04 11:02 UTC, cbeneke commented on pages/04.tutorials/23.use-external-dns/default.en.md
> +## Setting up ExternalDNS for Services on AWS
The indention of "Add this IAM Policy to your external-dns user" is h2 but should be h3 (The webinterface doesn't allow me to comment on non-edited lines, thats why its here)

2019-09-04 11:02 UTC, cbeneke commented on pages/04.tutorials/23.use-external-dns/default.en.md
> +### First add a new IAM user to your AWS account
I would drop the 'First' here, because its a heading not a sentence

2019-09-04 11:02 UTC, cbeneke commented on pages/04.tutorials/23.use-external-dns/default.en.md
> +
One newline is sufficient

2019-09-06 08:51 UTC, merged